### ISSUE TITLE
Current update has rendered it obsolete...

### ISSUE THREAD

**Issue by DLI1996** [goodwin64/Endorse-all-skills-LinkedIn#1]
Now, for each endorsement, you have to add two comments: 
1. How good is XXX at XXX?
2. How do you know about XXX's XXX skill?

**Comment by MaxDonchenko** [comment]
You can ignore this popup, endorsements got applied anyway:

![ezgif-6-913b905296da](https://user-images.githubusercontent.com/10671879/94442714-f3219880-01ac-11eb-97aa-d884f5e5bdf4.gif)

**Comment by DLI1996** [comment]
Thanks!

**Comment by MaxDonchenko** [comment]
You're welcome :)
